// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArTVuV-gCueJ2Vroq8c8N09za1K5nXyuo',
    appId: '1:438944611788:web:dc68af136b7deeacfaf169',
    messagingSenderId: '438944611788',
    projectId: 'healthcareapp-1f30c',
    authDomain: 'healthcareapp-1f30c.firebaseapp.com',
    storageBucket: 'healthcareapp-1f30c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3i1i1sduGnn0HICh6rDm4Dftw8iTNKo',
    appId: '1:438944611788:android:2a7b9cadf5bf83d3faf169',
    messagingSenderId: '438944611788',
    projectId: 'healthcareapp-1f30c',
    storageBucket: 'healthcareapp-1f30c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9zelV_f3D75c4HAyYUs2ybb1B6It5kw',
    appId: '1:438944611788:ios:90474c18ddde6acffaf169',
    messagingSenderId: '438944611788',
    projectId: 'healthcareapp-1f30c',
    storageBucket: 'healthcareapp-1f30c.firebasestorage.app',
    iosBundleId: 'com.example.untitled22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9zelV_f3D75c4HAyYUs2ybb1B6It5kw',
    appId: '1:438944611788:ios:90474c18ddde6acffaf169',
    messagingSenderId: '438944611788',
    projectId: 'healthcareapp-1f30c',
    storageBucket: 'healthcareapp-1f30c.firebasestorage.app',
    iosBundleId: 'com.example.untitled22',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArTVuV-gCueJ2Vroq8c8N09za1K5nXyuo',
    appId: '1:438944611788:web:4727c0458f4843a0faf169',
    messagingSenderId: '438944611788',
    projectId: 'healthcareapp-1f30c',
    authDomain: 'healthcareapp-1f30c.firebaseapp.com',
    storageBucket: 'healthcareapp-1f30c.firebasestorage.app',
  );
}
